[package]
name = "my_webgl_app"
version = "0.1.0"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"  # Bindgen for JavaScript interop

[lib]
crate-type = ["cdylib"]  # Compile as a dynamic library (WASM)
