[package]
name = "my_webgl_app"
version = "0.1.0"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"  # Bindgen for JavaScript interop
rustfft = "6.0"
web-sys = { version = "0.3.70", features = ["console"] }

[lib]
crate-type = ["cdylib"]  # Compile as a dynamic library (WASM)
